using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace scraping_mvc.Migrations
{
    public partial class InitialCreate : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "FoodItems",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    Title = table.Column<string>(nullable: true),
                    Description = table.Column<string>(nullable: true),
                    Price = table.Column<int>(nullable: false),
                    Category = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_FoodItems", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "LunchItems",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    Title = table.Column<string>(nullable: true),
                    Description = table.Column<string>(nullable: true),
                    Price = table.Column<int>(nullable: false),
                    Category = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_LunchItems", x => x.Id);
                });

            migrationBuilder.InsertData(
                table: "FoodItems",
                columns: new[] { "Id", "Category", "Description", "Price", "Title" },
                values: new object[,]
                {
                    { 1, "SPECIALITETER / A LA CARTE", "200 gram kyllingefilet, kartoffelbåde, hjemmelavet bearnaisesauce, tzatziki", 189, "121. Kyllingefilet" },
                    { 158, "Familie-Almindelig Pizza", "Pizzasauce, ost, kylling, champignon, jalapeños, dressing (Dressing i ovn)", 195, "280. Simons special" },
                    { 159, "Familie-Almindelig Pizza", "Pizzasauce, ost, pepperoni, kebab, grøn peber, løg, dressing (Dressing i ovn)", 195, "281. Sengal" },
                    { 160, "Familie-Almindelig Pizza", "Pizzasauce, ost, salami, champignon, paprika, oksekød, dressing (Dressing i ovn)", 195, "283. Kobeni" },
                    { 161, "Familie-Salat Pizza", "Pizzasauce, ost, spaghetti, kødsauce, salat, dressing", 205, "34. Memo &amp; Zin" },
                    { 162, "Familie-Salat Pizza", "Pizzasauce, ost, kebab, oksekød, salat, dressing", 205, "35. Domkirke" },
                    { 163, "Familie-Salat Pizza", "Pizzasauce, ost, kogt skinke, kylling, salat, dressing", 205, "36. Jakamoz" },
                    { 164, "Familie-Salat Pizza", "Pizzasauce, ost, pepperoni, pølser, bacon, salat, dressing", 205, "37. Ateza" },
                    { 165, "Familie-Salat Pizza", "Ost, kebab, pepperoni, salat, dressing", 205, "38. Viking" },
                    { 166, "Familie-Salat Pizza", "Ost, kogt skinke, pepperoni, salat, dressing", 205, "39. Avatar" },
                    { 167, "Familie-Salat Pizza", "Ost, kebab, kylling, salat, dressing", 205, "40. Serdal" },
                    { 168, "Familie-Mexicansk Pizza", "Pizzasauce, ost, kogt skinke, bacon, pølser, løg, oksekød, ekstra ost", 205, "50. Lufthavn" },
                    { 169, "Familie-Mexicansk Pizza", "Pizzasauce, ost, oksekød, pepperoni, champignon, løg, jalapeños, tacosauce", 205, "51. Santa Maria" },
                    { 157, "Familie-Almindelig Pizza", "Pizzasauce, ost, kebab, pepperoni, oksekød, paprika", 195, "33. Gunar" },
                    { 170, "Familie-Mexicansk Pizza", "Pizzasauce, ost, kylling, kebab, jalapeños, tacosauce, hvidløg", 205, "52. Amigo" },
                    { 172, "Familie-Mexicansk Pizza", "Pizzasauce, ost, oksefilet, champignon, løg, jalapeños, tacosauce, hvidløg", 205, "54. Zogros" },
                    { 173, "Familie-Mexicansk Pizza", "Pizzasauce, ost, pepperoni, pølser, ananas, bacon, jalapeños", 205, "55. Salamio" },
                    { 174, "Familie-Mexicansk Pizza", "Pizzasauce, ost, kogt skinke, pepperoni, løg, paprika, jalapeños", 205, "56. Ji’an" },
                    { 175, "Familie-Mexicansk Pizza", "Pizzasauce, ost, skinke, kebab, kødsauce, oksekød, chili, dressing", 205, "56B. Landgo" },
                    { 176, "Familie-Luksus Kapital Pizza", "Pizzasauce, ost, oksefilet strimler, champignon, løg, grøn peber, hjemmelavet bearnaisesauce", 205, "57. Apendos" },
                    { 177, "Familie-Luksus Kapital Pizza", "Pizzasauce, ost, oksefilet strimler, bacon, pepperoni, frisk tomat", 205, "58. Ciao ciao" },
                    { 178, "Familie-Luksus Kapital Pizza", "Pizzasauce, ost, oksefilet strimler, gorgonzola, løg, artiskok", 205, "59. Black Bella" },
                    { 179, "Familie-Luksus Kapital Pizza", "Pizzasauce, ost, oksefilet strimler, svinemørbrad, tortillachips, tacosauce", 205, "60. Nachos" },
                    { 180, "Familie-Luksus Kapital Pizza", "Pizzasauce, ost, svinemørbrad, champignon, grøn peber, gorgonzola, tomat", 205, "61. Odense" },
                    { 181, "Familie-Luksus Kapital Pizza", "Pizzasauce, ost, svinemørbrad, pepperoni, oksekød, løg", 205, "62. Ezel" },
                    { 182, "Familie-Luksus Kapital Pizza", "Pizzasauce, ost, svinemørbrad, kebab, bacon, chili, hjemmelavet bearnaisesauce", 205, "63. Venedig" },
                    { 183, "Familie-Parmaskinke / Mozarellaost Pizza", "Pizzasauce, mozarellaost, parmaskinke, pepperoni, champignon, pølser", 205, "64. Parma special" },
                    { 171, "Familie-Mexicansk Pizza", "Pizzasauce, ost, bacon, oksekød, kylling, jalapeños, tacosauce", 205, "53. Jalapeño" },
                    { 156, "Familie-Almindelig Pizza", "Pizzasauce, ost, kogt skinke, pepperoni, kylling, hjemmelavet bearnaisesauce", 195, "32. Marco Polo" },
                    { 155, "Familie-Almindelig Pizza", "Pizzasauce, ost, kylling, kebab, løg, champignon, spaghetti, dressing (Dressing i ovn)", 195, "31. Pilot special" },
                    { 154, "Familie-Almindelig Pizza", "Pizzasauce, ost, kebab, hakket oksekød, løg, chili, dressing (Dressing i ovn)", 195, "30. Kokkens fantasi" },
                    { 126, "Familie-Almindelig Pizza", "Tomatsauce, ost, kogt skinke", 170, "2. Vesuvio" },
                    { 127, "Familie-Almindelig Pizza", "Pizzasauce, ost, oksekød, chili", 170, "3. Afrika" },
                    { 128, "Familie-Almindelig Pizza", "Pizzasauce, ost, kogt skinke, ananas", 170, "4. Hawaii" },
                    { 129, "Familie-Almindelig Pizza", "Pizzasauce, ost, kogt skinke, spaghetti", 170, "5. Charlotte" },
                    { 130, "Familie-Almindelig Pizza", "Pizzasauce, ost, kogt skinke, pølser", 170, "6. Maria" },
                    { 131, "Familie-Almindelig Pizza", "Pizzasauce, ost, tun, løg, majs", 170, "7. Rino" },
                    { 132, "Familie-Almindelig Pizza", "Pizzasauce, ost, pepperoni, paprika", 170, "8. Uno" },
                    { 133, "Familie-Almindelig Pizza", "Pizzasauce, ost, bacon, løg, æg", 170, "9. Fanø" },
                    { 134, "Familie-Almindelig Pizza", "Pizzasauce, ost, spaghetti, kødsauce", 170, "10. Dynamit" },
                    { 135, "Familie-Almindelig Pizza", "Pizzasauce, ost, champignon, kylling, ananas", 185, "11. Kyllingpizza" },
                    { 136, "Familie-Almindelig Pizza", "Pizzasauce, ost, champignong, løg, paprika, majs, ærter, artiskok", 185, "12. Vegetariane" },
                    { 137, "Familie-Almindelig Pizza", "Pizzasauce, ost, tun, rejer, muslinger", 185, "13. Havet" },
                    { 138, "Familie-Almindelig Pizza", "Pizzasauce, ost, oksekød, pepperoni, paprika, chili", 185, "14. Babas" },
                    { 139, "Familie-Almindelig Pizza", "Pizzasauce, ost, kogt skinke, pepperoni, hakket oksekød", 185, "15. Mamas" },
                    { 140, "Familie-Almindelig Pizza", "Pizzasauce, ost, kogt skinke, bacon, pølser", 185, "16. Mama Rosa" },
                    { 141, "Familie-Almindelig Pizza", "Pizzasauce, ost, kogt skinke, champignon, oksekød", 185, "17. Matador" },
                    { 142, "Familie-Almindelig Pizza", "Pizzasauce, ost, kogt skinke, bacon, hjemmelavet bearnaisesauce", 185, "18. Herkules" },
                    { 143, "Familie-Almindelig Pizza", "Pizzasauce, ost, rejer, bacon, pølser", 185, "19. Manhattan" },
                    { 144, "Familie-Almindelig Pizza", "Pizzasauce, ost, kebab, løg, paprika, gorgonzola", 185, "20. Botan" },
                    { 145, "Familie-Almindelig Pizza", "Pizzasauce, ost, kogt skinke, løg, oksekød, bacon", 195, "21. Unge mand" },
                    { 146, "Familie-Almindelig Pizza", "Pizzasauce, ost, kogt skinke, kebab, pepperoni", 195, "22. Unge pige" },
                    { 147, "Familie-Almindelig Pizza", "Pizzasauce, ost, spaghetti, kogt skinke, kødsauce, pølser", 195, "23. Københavner" },
                    { 148, "Familie-Almindelig Pizza", "Pizzasauce, ost, løg, kødsauce, pepperoni, feta", 195, "24. Sct. Peders" },
                    { 149, "Familie-Almindelig Pizza", "Pizzasauce, ost, spaghetti, kødsauce, kebab, paprika", 195, "25. Mama mia" },
                    { 150, "Familie-Almindelig Pizza", "Pizzasauce, ost, løg, kebab, paprika, asparges, chili", 195, "26. Kurdisk" },
                    { 151, "Familie-Almindelig Pizza", "Pizzasauce, ost, champignon, pølser, oksekød, hjemmelavet bearnaisesauce", 195, "27. Jylland" },
                    { 152, "Familie-Almindelig Pizza", "Pizzasauce, ost, kebab, pølser, bacon, chili", 195, "28. Dracula" },
                    { 184, "Familie-Parmaskinke / Mozarellaost Pizza", "Pizzasauce, mozarellaost, parmaskinke, tomat, rucola salat, svinemørbrad, hjemmelavet bearnaisesauce", 205, "65. Inferno" },
                    { 185, "Familie-Parmaskinke / Mozarellaost Pizza", "Pizzasauce, mozarellaost, parmaskinke, champignon, artiskok, italiensk salami", 205, "66. Palermo" },
                    { 186, "Familie-Parmaskinke / Mozarellaost Pizza", "Pizzasauce, mozarellaost, parmaskinke, kylling, italiensk salami", 205, "67. Kolding" },
                    { 187, "Familie-Parmaskinke / Mozarellaost Pizza", "Pizzasauce, mozarellaost, parmaskinke, fetaost, tomat, grøn peber, rucola salat", 205, "68. Milano" },
                    { 219, "Pasta", "Bacon, æg, skinke, flødesauce, salat, hjemmelavet flutes", 95, "91. Spaghetti carbonara" },
                    { 220, "Pasta", "Kylling, ananas, paprika, karry, flødesauce, salat, hjemmelavet flutes", 95, "92. Spaghetti Indiana" },
                    { 221, "Pasta", "Oksefilet, champignon, grøn peber, flødesauce, salat, hjemmelavet flutes", 95, "93. Penne" },
                    { 222, "Pasta", "Svinemørbrad, løg, gorgonzola, paprika, flødesauce, salat, hjemmelavet flutes", 95, "94. Penne" },
                    { 223, "Pasta", "Kebab, kødsauce, løg, champignon, paprika, jalapeños, flødesauce, salat, hjemmelavet flutes", 95, "95. Penne" },
                    { 224, "Pasta", "Kæmpe rejer, løg, hvidløg, flødesauce, salat, hjemmelavet flutes", 95, "96. Penne" },
                    { 225, "Pasta", "Skinke, bacon, pølser, flødesauce, salat, hjemmelavet flutes", 95, "97. Tortellini" },
                    { 226, "Pasta", "Champignon, paprika, løg, artiskok, oliven, ærter, majs, salat, hjemmelavet flutes", 95, "97B. Penne vegetar" },
                    { 227, "Pasta", "Kylling, løg, bacon, flødesauce, salat, hjemmelavet flutes", 95, "97C. Penne" },
                    { 228, "Pasta", "Løg, champignon, paprika, spinat, flødesauce, salat, hjemmelavet flutes", 95, "97D. Spinat Tortellini" },
                    { 229, "Pasta", "Kebab, løg, kylling, spinat, flødesauce, salat, hjemmelavet flutes", 95, "97E. Spinat Penne" },
                    { 230, "Durum", "Salat, tomat, agurk, dressing", 75, "85. Durum kebab" },
                    { 231, "Durum", "Salat, tomat, agurk, dressing", 75, "86. Durum skinke" },
                    { 232, "Durum", "Salat, tomat, agurk, dressing", 75, "87. Durum tun" },
                    { 233, "Durum", "Salat, tomat, agurk, dressing", 75, "88. Durum kylling" },
                    { 234, "Durum", "Salat, tomat, agurk, dressing", 75, "88B. Durum rejer" },
                    { 235, "Sandwich", "Salat, tomat, agurk, ost, dressing", 75, "139. Sandwich kebab" },
                    { 236, "Sandwich", "Salat, tomat, agurk, ost, dressing", 75, "140. Sandwich kylling" },
                    { 237, "Sandwich", "Salat, tomat, agurk, ost, dressing", 75, "141. Sandwich pepperoni" },
                    { 238, "Sandwich", "Salat, tomat, agurk, ost, dressing", 75, "142. Sandwich skinke" },
                    { 239, "Sandwich", "Kødsauce, salat, tomat, agurk, ost, dressing", 75, "143. Sandwich spaghetti" },
                    { 240, "Pitabrød", "Salat, tomat, agurk, dressing", 60, "79. Pita kebab" },
                    { 241, "Pitabrød", "Salat, tomat, agurk, dressing", 60, "80. Pita bøf" },
                    { 242, "Pitabrød", "Salat, tomat, agurk, dressing", 60, "81. Pita skinke" },
                    { 243, "Pitabrød", "Salat, tomat, agurk, dressing", 60, "82. Pita rejer" },
                    { 244, "Pitabrød", "Salat, tomat, agurk, dressing", 60, "83. Pita tun" },
                    { 245, "Pitabrød", "Salat, tomat, agurk, dressing", 60, "84. Pita kylling" },
                    { 218, "Pasta", "Kødsauce, flødesauce, salat, hjemmelavet flutes", 95, "90. Spaghetti bolognese" },
                    { 125, "Familie-Almindelig Pizza", "Tomatsauce, ost", 170, "1. Margaherita" },
                    { 217, "Pasta", "Kødsauce, ost, salat, hjemmelavet flutes", 95, "89. Hjemmelavet lasagne" },
                    { 215, "Ekstra tilbehør", "Ost, skinke, tun, bacon, gorgonzola, oksekød, pepperoni, oksefiletstrimler, parmaskinke, muslinger, pølser, rejser, salat, kødsauce, kebab, kylling, jalapeños", 15, "Familie pizza" },
                    { 188, "Familie-Parmaskinke / Mozarellaost Pizza", "Pizzasauce, mozarellaost, italiensk salami, fetaost, løg, tomat, grøn peber, rucola salat", 205, "69. Al Capone" },
                    { 189, "Indbagt Pizza", "Pizzasauce, ost, kogt skinke, spaghetti, kødsauce", 75, "41. Billund" },
                    { 190, "Indbagt Pizza", "Pizzasauce, ost, løg, paprika, kebab, gorgonzola", 75, "42. Dillan" },
                    { 191, "Indbagt Pizza", "Pizzasauce, ost, kogt skinke, pepperoni, pølser", 75, "43. Layla" },
                    { 192, "Indbagt Pizza", "Pizzasauce, ost, kogt skinke, løg, champignon, kødsauce", 75, "44. Zana" },
                    { 193, "Indbagt Pizza", "Ost, løg, fetaost, kebab, rå tomat, smør", 75, "45. Kurdisk indbagt" },
                    { 194, "Åben Indbagt", "Pizzasauce, ost, løg, champignon, kebab, tomatskiver, dressing", 75, "46. Barut" },
                    { 195, "Åben Indbagt", "Pizzasauce, ost, spaghetti, kødsauce, paprika, dressing", 75, "47. Haco" },
                    { 196, "Åben Indbagt", "Pizzasauce, ost, kogt skinke, pepperoni, pølser, hjemmelavet bearnaisesauce", 75, "48. Cengo" },
                    { 197, "Åben Indbagt", "Pizzasauce, ost, løg, champignon, kylling, chili, dressing", 75, "49. Azad" },
                    { 198, "Børnepizza / Menu", "Pizzasauce, ost, spaghetti, kødsauce", 60, "73. Splinter" },
                    { 199, "Børnepizza / Menu", "Pizzasauce, ost, kogt skinke, pølser", 60, "74. Leonardo" },
                    { 200, "Børnepizza / Menu", "Pizzasauce, ost, kogt skinke, ananas", 60, "75. April O’Neil" },
                    { 201, "Børnepizza / Menu", "Pizzasauce, ost, spaghetti, kogt skinke", 60, "76. Raphael" },
                    { 202, "Børnepizza / Menu", "Pizzasauce, ost, kødsauce", 60, "77. Donatello" },
                    { 203, "Børnepizza / Menu", "Pizzasauce, ost, pepperoni", 60, "78. Michael Angelo" },
                    { 204, "Børnepizza / Menu", "Med ost og kødsauce", 60, "78B. Lasagne" },
                    { 205, "Børnepizza / Menu", "Med kødsauce og flødesauce", 60, "78C. Spaghetti Bolognese" },
                    { 206, "Børnepizza / Menu", "Med pommes frites, remoulade og ketchup", 60, "78D. Fiskefilet" },
                    { 207, "Half 'N Half Pizza", "Indbagt: Pizzasauce, ost, kogt skinke, spaghetti, kødsauce", 90, "70. Half ‘n Half" },
                    { 208, "Half 'N Half Pizza", "Alm.: Pizzasauce, ost, italiensk salami, kylling, salat, dressing", 90, "70. Half ‘n Half" },
                    { 209, "Half 'N Half Pizza", "Indbagt: Pizzasauce, ost, kebab, løg, gorgonzola", 90, "71. Half ‘n Half" },
                    { 210, "Half 'N Half Pizza", "Alm.: Pizzasauce, ost, kylling, paprika, bacon, ananas", 90, "71. Half ‘n Half" },
                    { 211, "Half 'N Half Pizza", "Indbagt: Pizzasauce, ost, kogt skinke, rejer, champignon", 90, "72. Half ‘n Half" },
                    { 212, "Half 'N Half Pizza", "Alm.: Pizzasauce, ost, italiensk salami, pølser, oksekød", 90, "72. Half ‘n Half" },
                    { 213, "Ekstra tilbehør", "Ost, skinke, tun, bacon, gorgonzola, oksekød, pepperoni, oksefiletstrimler, parmaskinke, muslinger, pølser, rejser, salat, kødsauce, kebab, kylling, jalapeños", 10, "Almindelig pizza" },
                    { 214, "Ekstra tilbehør", "Asparges, champignon, løg, majs, paprika, ananas, oliven, spaghetti, ærter, bearnaisesauce, dressing, tacosauce", 5, "Almindelig pizza" },
                    { 216, "Ekstra tilbehør", "Asparges, champignon, løg, majs, paprika, ananas, oliven, spaghetti, ærter, bearnaisesauce, dressing, tacosauce", 10, "Familie pizza" },
                    { 124, "Parmaskinke / Mozarellaost Pizza", "Pizzasauce, mozarellaost, italiensk salami, fetaost, løg, tomat, grøn peber, rucola salat", 90, "69. Al Capone" },
                    { 153, "Familie-Almindelig Pizza", "Pizzasauce, ost, pepperoni, oksekød, gorgonzola, æg", 195, "29. Casanova" },
                    { 122, "Parmaskinke / Mozarellaost Pizza", "Pizzasauce, mozarellaost, parmaskinke, kylling, italiensk salami", 90, "67. Kolding" },
                    { 33, "Luksus-salater", "Tunfisk, løg, oliven, peberfrugt, æg, citron, ærter, majs, tomat, agurk, hjemmelavet brød, dressing", 90, "104. Tun salat" },
                    { 34, "Luksus-salater", "Skinke, kylling, avocado, soltørrede tomater, løg, ærter, majs, tomat, agurk, hjemmelavet brød, dressing", 90, "105. Mixed salat" },
                    { 35, "Luksus-salater", "Champignon, artiskok, peberfrugt, løg, ananas, oliven, ærter, majs, tomat, agurk, hjemmelavet brød, dressing", 90, "106. Vegetar salat" },
                    { 36, "Luksus-salater", "Rejer, tunfisk, skinke, mozarellaost, soltørrede tomater, løg, ærter, majs, tomat, agurk, hjemmelavet brød, dressing", 90, "107. Husets salat" },
                    { 37, "Luksus-salater", "Kebab, løg, grøn peber, ærter, majs, tomat, agurk, hjemmelavet brød, dressing", 90, "107B. Kebab salat" },
                    { 38, "Mexicansk Fajitas", "Oksefilet, løg, pebermix, jalapeños, tacosauce, brød, hvidløgsauce, salat, dressing, kartoffelbåde", 189, "300. Oksefilet" },
                    { 39, "Mexicansk Fajitas", "Kylling, løg, pebermix, jalapeños, tacosauce, brød, hvidløgsauce, salat, dressing, kartoffelbåde", 189, "301. Kylling" },
                    { 40, "Mexicansk Fajitas", "Rejer, løg, pebermix, jalapeños, tacosauce, brød, hvidløgsauce, salat, dressing, kartoffelbåde", 189, "302. Rejer" },
                    { 41, "Forretter", "Hvidløgsbrød, ost", 45, "116. Hvidløgsbrød" },
                    { 42, "Forretter", "Rejecocktail", 55, "117. Rejecocktail" },
                    { 43, "Forretter", "6 stk. calamari", 55, "118. Calamari" },
                    { 44, "Forretter", "Tzatziki, flute", 55, "119. Tzatziki" },
                    { 45, "Forretter", "10 stk. indbagte rejer", 60, "120. Indbagte rejer" },
                    { 46, "Forretter", "Tortillachips, ost", 70, "136. Tortillachips" },
                    { 47, "Forretter", "Tortillachips, kylling, ost, tacosauce, hjemmelavet dressing", 75, "136B. Tortillachips" },
                    { 48, "Drikkevarer", "Husets vin", 160, "Husets vin" },
                    { 49, "Drikkevarer", "1½ ltr. flaske", 40, "Sodavand" },
                    { 50, "Drikkevarer", "Kildevand", 25, "Kildevand" },
                    { 51, "Steakhouse Burgere", "Bacon, 200 gram hakket oksekød, mixsalat, løg, tomater, agurk, burgerdressing, kartoffelbåde, mayonnaise", 115, "245. Steakhouse Bacon burger" },
                    { 52, "Steakhouse Burgere", "Ost, 200 gram hakket oksekød, mixsalat, løg, tomater, agurk, burgerdressing, kartoffelbåde, mayonnaise", 115, "246. Steakhouse Cheese burger" },
                    { 53, "Steakhouse Burgere", "200 gram hakket oksekød, mixsalat, løg, tomater, agurk, burgerdressing, kartoffelbåde, mayonnaise", 115, "247. Steakhouse Mexicansk burger" },
                    { 54, "Steakhouse Burgere", "Kylling, mixsalat, løg, tomater, agurk, burgerdressing, kartoffelbåde, mayonnaise", 115, "248. Steakhouse Kyllingsteak burger" },
                    { 55, "Almindelige Burgere", "160 gram oksekød, salat, tomat, agurk, rødløg, mayonnaise, burgerdressing", 60, "144. Classic" },
                    { 56, "Almindelige Burgere", "160 gram oksekød, bacon, salat, tomat, agurk, rødløg, mayonnaise, burgerdressing", 65, "145. Bacon" },
                    { 57, "Almindelige Burgere", "160 gram oksekød. ost, salat, tomat, agurk, rødløg, mayonnaise, burgerdressing", 65, "146. Cheese" },
                    { 58, "Almindelige Burgere", "160 gram oksekød, bacon, ost, salat, tomat, agurk, rødløg, mayonnaise, burgerdressing", 65, "147. Bacon cheese" },
                    { 59, "Almindelige Burgere", "160 gram oksekød, tacosauce, jalapeños, salat, tomat, agurk, rødløg, mayonnaise, burgerdressing", 70, "148. Mexicansk" },
                    { 123, "Parmaskinke / Mozarellaost Pizza", "Pizzasauce, mozarellaost, parmaskinke, fetaost, tomat, grøn peber, rucola salat", 90, "68. Milano" },
                    { 60, "Almindelige Burgere", "Kylling, salat, tomat, agurk, rødløg, mayonnaise, burgerdressing", 65, "149. Kylling" },
                    { 31, "Luksus-salater", "Skinke, ost, æg, løg, peberfrugt, ærter, majs, tomat, agurk, hjemmelavet brød, dressing", 90, "102. Skinke salat" },
                    { 29, "Luksus-salater", "Fetaost, oliven, løg, peberfrugt, artiskok, ærter, majs, tomat, agurk, hjemmelavet brød, dressing", 90, "100. Græsk salat" },
                    { 2, "SPECIALITETER / A LA CARTE", "200 gram kyllingefilet, kartoffelbåde, champignonsauce, tzatziki", 189, "122. Kyllingefilet" },
                    { 3, "SPECIALITETER / A LA CARTE", "200 gram oksefilet, kartoffelbåde, hjemmelavet bearnaisesauce, tzatziki", 209, "123. Oksefilet" },
                    { 4, "SPECIALITETER / A LA CARTE", "Okse, kylling, lam, hakket oksekød, kartoffelskiver, champignonsauce", 219, "124. Mix" },
                    { 5, "SPECIALITETER / A LA CARTE", "200 gram oksefilet, kartoffelskiver, whiskeysauce, tzatziki", 209, "125. Oksefilet" },
                    { 6, "SPECIALITETER / A LA CARTE", "200 gram oksefilet, kartoffelskiver, mozarellaost, parmaskinke, tomatsauce, tzatziki", 209, "126. Oksefilet" },
                    { 7, "SPECIALITETER / A LA CARTE", "200 gram oksefilet, ovnbagt kartoffelmos, hjemmelavet bearnaisesauce/champignonsauce", 209, "127. Plankesteak" },
                    { 8, "SPECIALITETER / A LA CARTE", "200 gram oksefilet, kartoffelbåde, gorgonzola, tzatziki", 209, "128. Oksefilet" },
                    { 9, "SPECIALITETER / A LA CARTE", "200 gram oksefilet, kartoffelbåde, champignonsauce, tzatziki", 209, "129. Oksefilet" },
                    { 10, "SPECIALITETER / A LA CARTE", "3 stk. lammekoteletter, kartoffelskiver, champignonsauce, tzatziki", 209, "130. Lammekoteletter" },
                    { 11, "SPECIALITETER / A LA CARTE", "Kyllingefilet, ovnbagt kartoffelmos, hjemmelavet bearnaisesauce", 209, "131. Plankesteak" },
                    { 12, "SPECIALITETER / A LA CARTE", "300 gram T-bone steak, kartoffelskiver, hjemmelavet bearnaisesauce, tzatziki", 209, "132. T-bone steak" },
                    { 13, "SPECIALITETER / A LA CARTE", "250 gram hakket oksekød, kartoffelbåde, gorgonzolasauce, tzatziki", 195, "133. Plankebøf" },
                    { 14, "SPECIALITETER / A LA CARTE", "250 gram hakket oksekød, kartoffelskiver, hjemmelavet bearnaisesauce, tzatziki", 195, "134. Græsk bøf" },
                    { 15, "SPECIALITETER / A LA CARTE", "Pandestegt oksefilet strimler, champignon, pebermix, tomater, løg, kartoffelbåde, flødesauce, tzatziki", 195, "135. Sultankebab" },
                    { 16, "SPECIALITETER / A LA CARTE", "Svinemørbrad, kartoffelskiver", 209, "137. Svinemørbrad" },
                    { 17, "SPECIALITETER / A LA CARTE", "Entrecote, kartoffelskiver, hjemmelavet bearnaisesauce", 219, "138. Entrecote" },
                    { 18, "Grillretter", "6 stk. kyllinge nuggets, pommes frites, ketchup, remoulade", 60, "108. Kyllinge nuggets" },
                    { 19, "Grillretter", "Pølser, pommes frites, karry ketchup, rå løg", 80, "109. Pølsemix" },
                    { 20, "Grillretter", "Kylling, pommes frites, salat, dressing", 80, "110. Kyllingemix" },
                    { 21, "Grillretter", "Kebab, pommes frites, salat, dressing", 80, "111. Kebabmix" },
                    { 22, "Grillretter", "½ Grill kylling (450 gram), pommes frites, agurksalat, ketchup, remoulade", 85, "112. Grill kylling" },
                    { 23, "Grillretter", "2 stk. fiskefilet, pommes frites, salat, dressing, ketchup, remoulade", 80, "113. Fiskefilet" },
                    { 24, "Grillretter", "Skinkeschnitzel, pommes frites, hjemmelavet bearnaisesauce, salat, dressing", 95, "114. Skinkeschnitzel" },
                    { 25, "Grillretter", "Kalkunschnitzel, pommes frites, hjemmelavet bearnaisesauce, salat, dressing", 95, "115. Kalkunschnitzel" },
                    { 26, "Grillretter", "Pommes frites, ketchup, remoulade", 40, "115B. Mellem pommes frites" },
                    { 27, "Luksus-salater", "Avocado, skinke, rejer, æg, ærter, majs, citron, tomat, agurk, hjemmelavet brød, dressing", 90, "98. Avocadosalat" },
                    { 28, "Luksus-salater", "Parmaskinke, mozarellaost, løg, soltørrede tomater, rucola salat, ærter, majs, tomat, agurk, hjemmelavet brød, dressing", 90, "99. Parmaskinke salat" },
                    { 30, "Luksus-salater", "Kylling, ananas, løg, peberfrugt, ærter, majs, tomat, agurk, hjemmelavet brød, dressing", 90, "101. Kyllinge salat" },
                    { 61, "Almindelig Pizza", "Tomatsauce, ost", 65, "1. Margaherita" },
                    { 32, "Luksus-salater", "Rejer, champignon, ananas, løg, æg, citron, ærter, majs, tomat, agurk, hjemmelavet brød, dressing", 90, "103. Reje salat" },
                    { 63, "Almindelig Pizza", "Pizzasauce, ost, oksekød, chili", 65, "3. Afrika" },
                    { 95, "Almindelig Pizza", "Pizzasauce, ost, pepperoni, kebab, grøn peber, løg, dressing (Dressing i ovn)", 80, "281. Sengal" },
                    { 96, "Almindelig Pizza", "Pizzasauce, ost, salami, champignon, paprika, oksekød, dressing (Dressing i ovn)", 80, "283. Kobeni" },
                    { 97, "Salat Pizza", "Pizzasauce, ost, spaghetti, kødsauce, salat, dressing", 80, "34. Memo &amp; Zin" },
                    { 98, "Salat Pizza", "Pizzasauce, ost, kebab, oksekød, salat, dressing", 80, "35. Domkirke" },
                    { 99, "Salat Pizza", "Pizzasauce, ost, kogt skinke, kylling, salat, dressing", 80, "36. Jakamoz" },
                    { 100, "Salat Pizza", "Pizzasauce, ost, pepperoni, pølser, bacon, salat, dressing", 80, "37. Ateza" },
                    { 101, "Salat Pizza", "Ost, kebab, pepperoni, salat, dressing", 80, "38. Viking" },
                    { 102, "Salat Pizza", "Ost, kogt skinke, pepperoni, salat, dressing", 80, "39. Avatar" },
                    { 103, "Salat Pizza", "Ost, kebab, kylling, salat, dressing", 80, "40. Serdal" },
                    { 104, "Mexicansk Pizza", "Pizzasauce, ost, kogt skinke, bacon, pølser, løg, oksekød, ekstra ost", 90, "50. Lufthavn" },
                    { 105, "Mexicansk Pizza", "Pizzasauce, ost, oksekød, pepperoni, champignon, løg, jalapeños, tacosauce", 90, "51. Santa Maria" },
                    { 107, "Mexicansk Pizza", "Pizzasauce, ost, bacon, oksekød, kylling, jalapeños, tacosauce", 90, "53. Jalapeño" },
                    { 108, "Mexicansk Pizza", "Pizzasauce, ost, oksefilet, champignon, løg, jalapeños, tacosauce, hvidløg", 90, "54. Zogros" },
                    { 109, "Mexicansk Pizza", "Pizzasauce, ost, pepperoni, pølser, ananas, bacon, jalapeños", 90, "55. Salamio" },
                    { 110, "Mexicansk Pizza", "Pizzasauce, ost, kogt skinke, pepperoni, løg, paprika, jalapeños", 90, "56. Ji’an" },
                    { 111, "Mexicansk Pizza", "Pizzasauce, ost, skinke, kebab, kødsauce, oksekød, chili, dressing", 90, "56B. Landgo" },
                    { 112, "Luksus Kapital Pizza", "Pizzasauce, ost, oksefilet strimler, champignon, løg, grøn peber, hjemmelavet bearnaisesauce", 90, "57. Apendos" },
                    { 113, "Luksus Kapital Pizza", "Pizzasauce, ost, oksefilet strimler, bacon, pepperoni, frisk tomat", 90, "58. Ciao ciao" },
                    { 114, "Luksus Kapital Pizza", "Pizzasauce, ost, oksefilet strimler, gorgonzola, løg, artiskok", 90, "59. Black Bella" },
                    { 115, "Luksus Kapital Pizza", "Pizzasauce, ost, oksefilet strimler, svinemørbrad, tortillachips, tacosauce", 90, "60. Nachos" },
                    { 116, "Luksus Kapital Pizza", "Pizzasauce, ost, svinemørbrad, champignon, grøn peber, gorgonzola, tomat", 90, "61. Odense" },
                    { 117, "Luksus Kapital Pizza", "Pizzasauce, ost, svinemørbrad, pepperoni, oksekød, løg", 90, "62. Ezel" },
                    { 118, "Luksus Kapital Pizza", "Pizzasauce, ost, svinemørbrad, kebab, bacon, chili, hjemmelavet bearnaisesauce", 90, "63. Venedig" },
                    { 119, "Parmaskinke / Mozarellaost Pizza", "Pizzasauce, mozarellaost, parmaskinke, pepperoni, champignon, pølser", 90, "64. Parma special" },
                    { 120, "Parmaskinke / Mozarellaost Pizza", "Pizzasauce, mozarellaost, parmaskinke, tomat, rucola salat, svinemørbrad, hjemmelavet bearnaisesauce", 90, "65. Inferno" },
                    { 121, "Parmaskinke / Mozarellaost Pizza", "Pizzasauce, mozarellaost, parmaskinke, champignon, artiskok, italiensk salami", 90, "66. Palermo" },
                    { 62, "Almindelig Pizza", "Tomatsauce, ost, kogt skinke", 65, "2. Vesuvio" },
                    { 94, "Almindelig Pizza", "Pizzasauce, ost, kylling, champignon, jalapeños, dressing (Dressing i ovn)", 80, "280. Simons special" },
                    { 93, "Almindelig Pizza", "Pizzasauce, ost, kebab, pepperoni, oksekød, paprika", 80, "33. Gunar" },
                    { 106, "Mexicansk Pizza", "Pizzasauce, ost, kylling, kebab, jalapeños, tacosauce, hvidløg", 90, "52. Amigo" },
                    { 65, "Almindelig Pizza", "Pizzasauce, ost, kogt skinke, spaghetti", 65, "5. Charlotte" },
                    { 64, "Almindelig Pizza", "Pizzasauce, ost, kogt skinke, ananas", 65, "4. Hawaii" },
                    { 92, "Almindelig Pizza", "Pizzasauce, ost, kogt skinke, pepperoni, kylling, hjemmelavet bearnaisesauce", 80, "32. Marco Polo" },
                    { 66, "Almindelig Pizza", "Pizzasauce, ost, kogt skinke, pølser", 65, "6. Maria" },
                    { 67, "Almindelig Pizza", "Pizzasauce, ost, tun, løg, majs", 65, "7. Rino" },
                    { 68, "Almindelig Pizza", "Pizzasauce, ost, pepperoni, paprika", 65, "8. Uno" },
                    { 69, "Almindelig Pizza", "Pizzasauce, ost, bacon, løg, æg", 65, "9. Fanø" },
                    { 70, "Almindelig Pizza", "Pizzasauce, ost, spaghetti, kødsauce", 65, "10. Dynamit" },
                    { 71, "Almindelig Pizza", "Pizzasauce, ost, champignon, kylling, ananas", 75, "11. Kyllingpizza" },
                    { 72, "Almindelig Pizza", "Pizzasauce, ost, champignong, løg, paprika, majs, ærter, artiskok", 75, "12. Vegetariane" },
                    { 74, "Almindelig Pizza", "Pizzasauce, ost, oksekød, pepperoni, paprika, chili", 75, "14. Babas" },
                    { 75, "Almindelig Pizza", "Pizzasauce, ost, kogt skinke, pepperoni, hakket oksekød", 75, "15. Mamas" },
                    { 76, "Almindelig Pizza", "Pizzasauce, ost, kogt skinke, bacon, pølser", 75, "16. Mama Rosa" },
                    { 77, "Almindelig Pizza", "Pizzasauce, ost, kogt skinke, champignon, oksekød", 75, "17. Matador" },
                    { 78, "Almindelig Pizza", "Pizzasauce, ost, kogt skinke, bacon, hjemmelavet bearnaisesauce", 75, "18. Herkules" },
                    { 73, "Almindelig Pizza", "Pizzasauce, ost, tun, rejer, muslinger", 75, "13. Havet" },
                    { 90, "Almindelig Pizza", "Pizzasauce, ost, kebab, hakket oksekød, løg, chili, dressing (Dressing i ovn)", 80, "30. Kokkens fantasi" },
                    { 91, "Almindelig Pizza", "Pizzasauce, ost, kylling, kebab, løg, champignon, spaghetti, dressing (Dressing i ovn)", 80, "31. Pilot special" },
                    { 79, "Almindelig Pizza", "Pizzasauce, ost, rejer, bacon, pølser", 75, "19. Manhattan" },
                    { 89, "Almindelig Pizza", "Pizzasauce, ost, pepperoni, oksekød, gorgonzola, æg", 80, "29. Casanova" },
                    { 88, "Almindelig Pizza", "Pizzasauce, ost, kebab, pølser, bacon, chili", 80, "28. Dracula" },
                    { 87, "Almindelig Pizza", "Pizzasauce, ost, champignon, pølser, oksekød, hjemmelavet bearnaisesauce", 80, "27. Jylland" },
                    { 85, "Almindelig Pizza", "Pizzasauce, ost, spaghetti, kødsauce, kebab, paprika", 80, "25. Mama mia" },
                    { 86, "Almindelig Pizza", "Pizzasauce, ost, løg, kebab, paprika, asparges, chili", 80, "26. Kurdisk" },
                    { 83, "Almindelig Pizza", "Pizzasauce, ost, spaghetti, kogt skinke, kødsauce, pølser", 80, "23. Københavner" },
                    { 82, "Almindelig Pizza", "Pizzasauce, ost, kogt skinke, kebab, pepperoni", 80, "22. Unge pige" },
                    { 81, "Almindelig Pizza", "Pizzasauce, ost, kogt skinke, løg, oksekød, bacon", 80, "21. Unge mand" },
                    { 80, "Almindelig Pizza", "Pizzasauce, ost, kebab, løg, paprika, gorgonzola", 75, "20. Botan" },
                    { 84, "Almindelig Pizza", "Pizzasauce, ost, løg, kødsauce, pepperoni, feta", 80, "24. Sct. Peders" }
                });

            migrationBuilder.InsertData(
                table: "LunchItems",
                columns: new[] { "Id", "Category", "Description", "Price", "Title" },
                values: new object[,]
                {
                    { 40, "Pasta", "Kebab, kødsauce, løg, champignon, paprika, jalapeños, flødesauce, salat, hjemmelavet flutes", 60, "95. Penne" },
                    { 43, "Pasta", "Champignon, paprika, løg, artiskok, oliven, ærter, majs, salat, hjemmelavet flutes", 60, "97B. Penne vegetar" },
                    { 42, "Pasta", "Skinke, bacon, pølser, flødesauce, salat, hjemmelavet flutes", 60, "97. Tortellini" },
                    { 41, "Pasta", "Kæmpe rejer, løg, hvidløg, flødesauce, salat, hjemmelavet flutes", 60, "96. Penne" },
                    { 39, "Pasta", "Svinemørbrad, løg, gorgonzola, paprika, flødesauce, salat, hjemmelavet flutes", 60, "94. Penne" },
                    { 33, "Sandwich", "Kødsauce, salat, tomat, agurk, ost, dressing", 50, "143. Sandwich spaghetti" },
                    { 37, "Pasta", "Kylling, ananas, paprika, karry, flødesauce, salat, hjemmelavet flutes", 60, "92. Spaghetti Indiana" },
                    { 36, "Pasta", "Bacon, æg, skinke, flødesauce, salat, hjemmelavet flutes", 60, "91. Spaghetti carbonara" },
                    { 35, "Pasta", "Kødsauce, flødesauce, salat, hjemmelavet flutes", 60, "90. Spaghetti bolognese" },
                    { 34, "Pasta", "Kødsauce, ost, salat, hjemmelavet flutes", 60, "89. Hjemmelavet lasagne" },
                    { 44, "Pasta", "Kylling, løg, bacon, flødesauce, salat, hjemmelavet flutes", 60, "97C. Penne" },
                    { 38, "Pasta", "Oksefilet, champignon, grøn peber, flødesauce, salat, hjemmelavet flutes", 60, "93. Penne" },
                    { 45, "Pasta", "Løg, champignon, paprika, spinat, flødesauce, salat, hjemmelavet flutes", 60, "97D. Spinat Tortellini" },
                    { 59, "Luksus-salater", "Champignon, artiskok, peberfrugt, løg, ananas, oliven, ærter, majs, tomat, agurk, hjemmelavet brød, dressing", 60, "106. Vegetar salat" },
                    { 47, "Steakhouse Burgere", "Bacon, 200 gram hakket oksekød, mixsalat, løg, tomater, agurk, burgerdressing, kartoffelbåde, mayonnaise", 89, "245. Steakhouse Bacon burger" },
                    { 48, "Steakhouse Burgere", "Ost, 200 gram hakket oksekød, mixsalat, løg, tomater, agurk, burgerdressing, kartoffelbåde, mayonnaise", 89, "246. Steakhouse Cheese burger" },
                    { 49, "Steakhouse Burgere", "200 gram hakket oksekød, mixsalat, løg, tomater, agurk, burgerdressing, kartoffelbåde, mayonnaise", 89, "247. Steakhouse Mexicansk burger" },
                    { 50, "Steakhouse Burgere", "Kylling, mixsalat, løg, tomater, agurk, burgerdressing, kartoffelbåde, mayonnaise", 89, "248. Steakhouse Kyllingsteak burger" },
                    { 51, "Luksus-salater", "Avocado, skinke, rejer, æg, ærter, majs, citron, tomat, agurk, hjemmelavet brød, dressing", 60, "98. Avocadosalat" },
                    { 52, "Luksus-salater", "Parmaskinke, mozarellaost, løg, soltørrede tomater, rucola salat, ærter, majs, tomat, agurk, hjemmelavet brød, dressing", 60, "99. Parmaskinke salat" },
                    { 53, "Luksus-salater", "Fetaost, oliven, løg, peberfrugt, artiskok, ærter, majs, tomat, agurk, hjemmelavet brød, dressing", 60, "100. Græsk salat" },
                    { 54, "Luksus-salater", "Kylling, ananas, løg, peberfrugt, ærter, majs, tomat, agurk, hjemmelavet brød, dressing", 60, "101. Kyllinge salat" },
                    { 55, "Luksus-salater", "Skinke, ost, æg, løg, peberfrugt, ærter, majs, tomat, agurk, hjemmelavet brød, dressing", 60, "102. Skinke salat" },
                    { 56, "Luksus-salater", "Rejer, champignon, ananas, løg, æg, citron, ærter, majs, tomat, agurk, hjemmelavet brød, dressing", 60, "103. Reje salat" },
                    { 57, "Luksus-salater", "Tunfisk, løg, oliven, peberfrugt, æg, citron, ærter, majs, tomat, agurk, hjemmelavet brød, dressing", 60, "104. Tun salat" },
                    { 58, "Luksus-salater", "Skinke, kylling, avocado, soltørrede tomater, løg, ærter, majs, tomat, agurk, hjemmelavet brød, dressing", 60, "105. Mixed salat" },
                    { 32, "Sandwich", "Salat, tomat, agurk, ost, dressing", 50, "142. Sandwich skinke" },
                    { 46, "Pasta", "Kebab, løg, kylling, spinat, flødesauce, salat, hjemmelavet flutes", 60, "97E. Spinat Penne" },
                    { 31, "Sandwich", "Salat, tomat, agurk, ost, dressing", 50, "141. Sandwich pepperoni" },
                    { 1, "Almindelig Pizza", "Tomatsauce, ost", 50, "1. Margaherita" },
                    { 29, "Sandwich", "Salat, tomat, agurk, ost, dressing", 50, "139. Sandwich kebab" },
                    { 60, "Luksus-salater", "Rejer, tunfisk, skinke, mozarellaost, soltørrede tomater, løg, ærter, majs, tomat, agurk, hjemmelavet brød, dressing", 60, "107. Husets salat" },
                    { 2, "Almindelig Pizza", "Tomatsauce, ost, kogt skinke", 50, "2. Vesuvio" },
                    { 3, "Almindelig Pizza", "Pizzasauce, ost, oksekød, chili", 50, "3. Afrika" },
                    { 4, "Almindelig Pizza", "Pizzasauce, ost, kogt skinke, ananas", 50, "4. Hawaii" },
                    { 5, "Almindelig Pizza", "Pizzasauce, ost, kogt skinke, spaghetti", 50, "5. Charlotte" },
                    { 6, "Almindelig Pizza", "Pizzasauce, ost, kogt skinke, pølser", 50, "6. Maria" },
                    { 7, "Almindelig Pizza", "Pizzasauce, ost, tun, løg, majs", 50, "7. Rino" },
                    { 8, "Almindelig Pizza", "Pizzasauce, ost, pepperoni, paprika", 50, "8. Uno" },
                    { 9, "Almindelig Pizza", "Pizzasauce, ost, bacon, løg, æg", 50, "9. Fanø" },
                    { 10, "Almindelig Pizza", "Pizzasauce, ost, spaghetti, kødsauce", 50, "10. Dynamit" },
                    { 11, "Salat Pizza", "Pizzasauce, ost, spaghetti, kødsauce, salat, dressing", 50, "34. Memo &amp; Zin" },
                    { 12, "Salat Pizza", "Pizzasauce, ost, kebab, oksekød, salat, dressing", 50, "35. Domkirke" },
                    { 13, "Salat Pizza", "Pizzasauce, ost, kogt skinke, kylling, salat, dressing", 50, "36. Jakamoz" },
                    { 30, "Sandwich", "Salat, tomat, agurk, ost, dressing", 50, "140. Sandwich kylling" },
                    { 14, "Salat Pizza", "Pizzasauce, ost, pepperoni, pølser, bacon, salat, dressing", 50, "37. Ateza" },
                    { 16, "Salat Pizza", "Ost, kogt skinke, pepperoni, salat, dressing", 50, "39. Avatar" },
                    { 17, "Salat Pizza", "Ost, kebab, kylling, salat, dressing", 50, "40. Serdal" },
                    { 18, "Pitabrød", "Salat, tomat, agurk, dressing", 45, "79. Pita kebab" },
                    { 19, "Pitabrød", "Salat, tomat, agurk, dressing", 45, "80. Pita bøf" },
                    { 20, "Pitabrød", "Salat, tomat, agurk, dressing", 45, "81. Pita skinke" },
                    { 21, "Pitabrød", "Salat, tomat, agurk, dressing", 45, "82. Pita rejer" },
                    { 22, "Pitabrød", "Salat, tomat, agurk, dressing", 45, "83. Pita tun" },
                    { 23, "Pitabrød", "Salat, tomat, agurk, dressing", 45, "84. Pita kylling" },
                    { 24, "Durum", "Salat, tomat, agurk, dressing", 50, "85. Durum kebab" },
                    { 25, "Durum", "Salat, tomat, agurk, dressing", 50, "86. Durum skinke" },
                    { 26, "Durum", "Salat, tomat, agurk, dressing", 50, "87. Durum tun" },
                    { 27, "Durum", "Salat, tomat, agurk, dressing", 50, "88. Durum kylling" },
                    { 28, "Durum", "Salat, tomat, agurk, dressing", 50, "88B. Durum rejer" },
                    { 15, "Salat Pizza", "Ost, kebab, pepperoni, salat, dressing", 50, "38. Viking" },
                    { 61, "Luksus-salater", "Kebab, løg, grøn peber, ærter, majs, tomat, agurk, hjemmelavet brød, dressing", 60, "107B. Kebab salat" }
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "FoodItems");

            migrationBuilder.DropTable(
                name: "LunchItems");
        }
    }
}
