name: ASP.NET Core CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build with dotnet
      run: dotnet build --configuration Release 
    - name: Publishing the API Web
      run: dotnet publish --configuration Release --output ./Release ./scraping-mvc.csproj -r win-x64 --self-contained true
    - name: Deploy to Azure
      uses: azure/appservice-actions/webapp@master
      with: 
        app-name: blogs-and-bmi-github-actions
        publish-profile: ${{ secrets.PUBLISH_PROFILE }}
        package: /home/runner/work/scraping-mvc/scraping-mvc/Release/